import { useMemo } from 'react';
import { useCountUp, useInView } from '../../hooks';
import { longDate, monthLabel, num, pct, rupees } from '../../utils/format';
import type { Core } from '../../types';

/**
 * The turn.
 *
 * Everything up to here reads like one person's life. The bank's own flag on
 * the card data says otherwise: for the last two years, most of the receipts
 * were generated by somebody else, and they behave almost exactly like the
 * cardholder — same hours, same categories, same towns. That is the finding
 * the rest of the project exists to set up.
 */

const W = 720;
const H = 200;

function curve(values: number[], peak: number): string {
  const step = W / (values.length - 1);
  return values
    .map((v, i) => `${i === 0 ? 'M' : 'L'}${(i * step).toFixed(1)} ${(H - (v / peak) * H).toFixed(1)}`)
    .join('');
}

/** Pass 08 — the half that was never theirs. */
export default function Anomaly({ core }: { core: Core }) {
  const g = core.ghost;
  const [ref, seen] = useInView<HTMLDivElement>('-40px');
  const shown = useCountUp(Math.round(g.share * 1000), seen, 1500) / 10;

  const peakHour = useMemo(() => Math.max(...g.hour, ...g.cleanHour), [g]);
  const monthPeak = useMemo(() => Math.max(...g.byMonth.map((m) => m[1])), [g.byMonth]);
  const catPeak = useMemo(() => Math.max(...g.byCat.map((c) => Math.max(c.ghost, c.clean))), [g.byCat]);

  return (
    <article className="act act--pad act--anomaly" ref={ref}>
      <header className="act__head">
        <h2 className="h-act">
          <span className="h-act__n">08</span> The copy
        </h2>
      </header>

      <div className="reveal">
        <p className="reveal__big">
          <span>{shown.toFixed(1)}%</span>
        </p>
        <p className="reveal__line">
          of the last two years of this card was flagged by the bank as somebody else&rsquo;s
          spending.
        </p>
        <p className="reveal__sub">
          {num(g.count)} charges. {rupees(g.amt, true)}. It begins {longDate(g.first)} and it is
          still going on {longDate(g.last)} — {num(g.gapDays)} days later, across{' '}
          {num(g.cities)} towns and {num(g.merchants)} merchants. Nobody stopped it.
        </p>
      </div>

      <section className="twin">
        <h3 className="h-sub">Nobody here keeps hours</h3>
        <p className="twin__note">
          The listening dial has a violent shape: a third of every song played here starts
          between midnight and 5am. The card has no shape at all. Plot both sets of charges
          across the clock and neither rises or falls — the busiest single hour takes only{' '}
          {pct(g.flatShare)} of the total, against an even share of 4.2%. The two lines do not
          even track each other ({g.hourCorr.toFixed(2)} correlation). What they have in common
          is the absence of a routine, which is why no hour of the day is a useful signal for
          telling the two apart.
        </p>
        <figure className="twin__fig">
          <svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Charges by hour, theirs against the cardholder's">
            {[0.25, 0.5, 0.75].map((f) => (
              <line key={f} x1="0" x2={W} y1={H * f} y2={H * f} className="twin__grid" />
            ))}
            <path d={`${curve(g.cleanHour, peakHour)}L${W} ${H}L0 ${H}Z`} className="twin__areaA" />
            <path d={`${curve(g.hour, peakHour)}L${W} ${H}L0 ${H}Z`} className="twin__areaB" />
            <path d={curve(g.cleanHour, peakHour)} className="twin__lineA" />
            <path d={curve(g.hour, peakHour)} className="twin__lineB" />
          </svg>
          <figcaption>
            <span className="key key--clean">the cardholder</span>
            <span className="key key--ghost">the other one</span>
            <span className="twin__axis">midnight → 11pm</span>
          </figcaption>
        </figure>
      </section>

      <section className="split">
        <div>
          <h3 className="h-sub">And nothing separates them by category</h3>
          <ul className="catBars">
            {g.byCat.map((c) => (
              <li key={c.k}>
                <span className="catBars__k">{c.k}</span>
                <span className="catBars__pair">
                  <i className="is-clean" style={{ width: `${(c.clean / catPeak) * 100}%` }} />
                  <i className="is-ghost" style={{ width: `${(c.ghost / catPeak) * 100}%` }} />
                </span>
                <span className="catBars__v">
                  {num(c.clean)} / {num(c.ghost)}
                </span>
              </li>
            ))}
          </ul>
          <p className="fine">
            Cardholder first, the other one second. Across every merchant class the disputed
            share sits between {pct(Math.min(...g.catSpread.map((c) => c.share)), 0)} and{' '}
            {pct(Math.max(...g.catSpread.map((c) => c.share)), 0)} — near enough to a coin
            toss that no single receipt ever looks like the wrong one.
          </p>
        </div>

        <div>
          <h3 className="h-sub">It never tapers</h3>
          <ul className="monthBars" aria-label="Disputed charges per month">
            {g.byMonth.map(([ym, n]) => (
              <li key={ym} title={`${monthLabel(ym)}: ${n}`}>
                <i style={{ height: `${(n / monthPeak) * 100}%` }} />
                <span className="sr-only">
                  {monthLabel(ym)}: {n} disputed charges
                </span>
              </li>
            ))}
          </ul>
          <p className="fine">
            {monthLabel(g.byMonth[0][0])} to {monthLabel(g.byMonth[g.byMonth.length - 1][0])}.
            Twenty-five consecutive months, no gap longer than a fortnight.
          </p>

          <h3 className="h-sub">The largest of them</h3>
          <ul className="bigList">
            {g.biggest.map(([date, merch, amt, city]) => (
              <li key={`${date}-${merch}-${amt}`}>
                <span className="bigList__d">{date}</span>
                <span className="bigList__m">
                  {merch}
                  <small>{city}</small>
                </span>
                <span className="bigList__a">{rupees(amt)}</span>
              </li>
            ))}
          </ul>
        </div>
      </section>

      <section className="coda">
        <p>
          Put the three records back together and the shape of a person is obvious: someone who
          bought milk almost every morning for three years, who moved on autos and trains, who
          played {core.eras[2].topArtist} more than anyone else and who did most of their living
          after midnight.
        </p>
        <p>
          Then the ledger stops, the card starts, and {pct(g.share)} of what follows belongs to
          someone else — buying the same kinds of things, in the same proportions, at every
          hour of the day, in towns the cardholder may never have seen. Every test that worked
          on the music fails here. The receipts cannot tell you which of the two you have been
          reading about.
        </p>
        <p className="coda__end">
          {num(core.meta.receipts)} receipts. One of them is yours too — you just have not been
          shown it yet.
        </p>
      </section>
    </article>
  );
}
